[package]
name = "mquictt"
version = "0.0.1"
edition = "2021"

[dependencies]
bytes = "1.0"
mqttbytes = "0.6"
quiche = { version = "0.10" }
thiserror = "1.0"
tokio = { version = "1.13", features = ["sync", "rt"] }
